baseURL = "https://rh-cloud-experts.netlify.app/experts/"
publishDir = "public/experts"
languageCode = 'en-us'
title = 'Red Hat Cloud Experts Documentation'
theme = "rhds"
DefaultContentLanguage = "en"

disableAliases = true

# as the official Hugo documentation recommends, we turn this off for this
# showcase; this allows the published site to be served by both http and https
canonifyURLs = false
# required for official documentation served from subfolder
relativeURLs = false
enableGitInfo = true

# defaultContentLanguageInSubdir= false
# enableMissingTranslationPlaceholders = false

[outputs]
  home = [ "HTML", "RSS", "REDIR" ]

[mediaTypes]
  [mediaTypes."text/netlify"]
    delimiter = ""

[outputFormats]
  [outputFormats.REDIR]
    mediatype      = "text/netlify"
    baseName       = "_redirects"
    isPlainText    = true
    notAlternative = true

# Site params
[params]
  disableInlineCopyToClipBoard = true
  editURL = 'https://github.com/rh-mobb/documentation/edit/main/content/'

# Code highlight configuration
[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "emacs"
  tabWidth = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
      unsafe = true
